import Head from 'next/head'
import styles from '../styles/modules/Home.module.scss'
import Banner from './components/Banner'
import Main from './components/Main'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nexon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner />
        <Main />
      </main>

    </div>
  )
}
